baseURL = 'https://infrahouse.com/'
copyright = "2023 InfraHouse Inc."
languageCode = 'en-us'
title = 'InfraHouse'
theme = 'beautifulhugo'
enableRobotsTXT = true

[Params]
homeTitle = "InfraHouse" # Set a different text for the header on the home page
logo = "https://cdn.infrahouse.com/images/ih-logo.png" # Expecting square dimensions
favicon = "https://cdn.infrahouse.com/images/favicon-light.png"
selfHosted = true
cdn = "https://cdn.infrahouse.com"

[menu]
[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Products'
pageRef = '/products'
weight = 20

[[menu.main]]
name = 'MySQL on AWS'
pageRef = '/products/mysql-on-aws'
parent = 'Products'
weight = 1

[[menu.main]]
name = 'ProxySQL on AWS'
pageRef = '/products/proxysql-on-aws'
parent = 'Products'
weight = 2

[[menu.main]]
name = 'Terraform CI/CD'
pageRef = '/products/terraform-ci-cd'
parent = 'Products'
weight = 3

[[menu.main]]
name = 'Python CI/CD'
pageRef = '/products/python-ci-cd'
parent = 'Products'
weight = 4


[[menu.main]]
name = 'Services'
pageRef = '/services'
weight = 30

[[menu.main]]
name = 'Remote DBA'
pageRef = '/services/remote-dba'
parent = 'Services'
weight = 1

[[menu.main]]
name = 'Database Consulting'
pageRef = '/services/database-consulting'
parent = 'Services'
weight = 2

[[menu.main]]
name = 'AWS Consulting'
pageRef = '/services/aws-consulting'
parent = 'Services'
weight = 3

[[menu.main]]
name = 'About'
pageRef = '/about'
weight = 40

[[menu.main]]
name = 'Contact'
pageRef = '/contact'
weight = 50



[author]
name = "InfraHouse Inc."
website = "https://infrahouse.com"
github = "infrahouse"
linkedin_inc = "infrahouse-inc"
email = "contact@infrahouse.com"
