############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "/blog"
weight = 2


# footer menu
[[footer]]
name = "Blog"
url = "/blog"
weight = 1

[[footer]]
name = "Contact Us"
url = "/contact"
weight = 2

