Document: infrahouse-com
Title: Debian infrahouse-com Manual
Author: <insert document author here>
Abstract: This manual describes what infrahouse-com is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/infrahouse-com/infrahouse-com.sgml.gz

Format: postscript
Files: /usr/share/doc/infrahouse-com/infrahouse-com.ps.gz

Format: text
Files: /usr/share/doc/infrahouse-com/infrahouse-com.text.gz

Format: HTML
Index: /usr/share/doc/infrahouse-com/html/index.html
Files: /usr/share/doc/infrahouse-com/html/*.html
