# This workflow will upload an infrahouse-com package when a new commit to main is pushed
---
name: infrahouse.com Continuous Deployment

on:  # yamllint disable-line rule:truthy
    push:
        branches: ["main"]
    workflow_dispatch:
        inputs:
            debug_enabled:
                type: "boolean"
                description: "Setup a temporary SSH access if a test fails"
                required: false
                default: false

permissions:
    id-token: write  # This is required for requesting the JWT
    contents: read

env:
    ROLE_ARN: "arn:aws:iam::493370826424:role/infrahouse-com-github"

jobs:
    deploy:
        runs-on: ["self-hosted", "hugo"]
        strategy:
            matrix:
                codename: ["jammy"]
        steps:
            - uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  role-to-assume: ${{ env.ROLE_ARN }}
                  role-session-name: github-action-cd
                  aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

            - name: clean previous artifacts
              run: |
                  rm -f ../infrahouse-com_*.deb

            - name: Build package
              run: |
                make package

            - name: Publish Debian package
              run: |
                  ih-s3-reprepro \
                    --aws-region ${{ secrets.AWS_DEFAULT_REGION }} \
                    --bucket infrahouse-release-${{ matrix.codename }} \
                    --gpg-key-secret-id packager-key-${{ matrix.codename }} \
                    --gpg-passphrase-secret-id packager-passphrase-${{ matrix.codename }} \
                    includedeb \
                    ${{ matrix.codename }} \
                    ../infrahouse-com_*.deb
