# This workflow will upload an infrahouse-com package when a new commit to main is pushed
---
name: infrahouse.com Continuous Integration

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
    deploy:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                codename: ["jammy"]
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                sudo bash support/install_deps.sh ${{ matrix.codename }}

            - name: Build package
              run: |
                OS_VERSION=${{ matrix.codename }} make package
